In [4]:
import pandas as pd
import numpy as np

In [8]:
path ="Datasets/iris.data"
names=['sepal-lenght','sepal-width','petal-lenght','petal-width','Target']
irisdata =pd.read_csv(path, names=names)
irisdata.head(10)

sepal-lenght  sepal-width  petal-lenght  petal-width       Target
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [9]:
print("Iris data set dimensions : {}".format(irisdata.shape))

Iris data set dimensions : (150, 5)


In [10]:
irisdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal-lenght    150 non-null float64
sepal-width     150 non-null float64
petal-lenght    150 non-null float64
petal-width     150 non-null float64
Target          150 non-null object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [11]:
irisdata.isnull().sum()
irisdata.isna().sum()

sepal-lenght    0
sepal-width     0
petal-lenght    0
petal-width     0
Target          0
dtype: int64

In [19]:
x=irisdata.iloc[:,0:4]
y=irisdata.iloc[:,4]
a=y.unique()
a

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [23]:
from sklearn import preprocessing 
y=pd.DataFrame(y)
le=preprocessing.LabelEncoder()
y=y.apply(le.fit_transform)
y.Target.unique()
y

Target
0         0
1         0
2         0
3         0
4         0
..      ...
145       2
146       2
147       2
148       2
149       2

[150 rows x 1 columns]

In [25]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train ,y_test =train_test_split(x,y, test_size=0.20)
y_train

Target
62        1
98        1
0         0
130       2
90        1
..      ...
21        0
72        1
61        1
32        0
111       2

[120 rows x 1 columns]

In [27]:
x_test

sepal-lenght  sepal-width  petal-lenght  petal-width
19            5.1          3.8           1.5          0.3
122           7.7          2.8           6.7          2.0
84            5.4          3.0           4.5          1.5
4             5.0          3.6           1.4          0.2
60            5.0          2.0           3.5          1.0
68            6.2          2.2           4.5          1.5
110           6.5          3.2           5.1          2.0
106           4.9          2.5           4.5          1.7
63            6.1          2.9           4.7          1.4
8             4.4          2.9           1.4          0.2
124           6.7          3.3           5.7          2.1
42            4.4          3.2           1.3          0.2
76            6.8          2.8           4.8          1.4
100           6.3          3.3           6.0          2.5
75            6.6          3.0           4.4          1.4
109           7.2          3.6           6.1          2.5
91            6.1          3.0           4.6          1.4
50            7.0          3.2           4.7          1.4
120           6.9          3.2           5.7          2.3
86            6.7          3.1           4.7          1.5
129           7.2          3.0           5.8          1.6
53            5.5          2.3           4.0          1.3
56            6.3          3.3           4.7          1.6
119           6.0          2.2           5.0          1.5
104           6.5          3.0           5.8          2.2
114           5.8          2.8           5.1          2.4
10            5.4          3.7           1.5          0.2
134           6.1          2.6           5.6          1.4
48            5.3          3.7           1.5          0.2
83            6.0          2.7           5.1          1.6

In [28]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train =scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[ 0.2512974 , -2.04197568,  0.21701102, -0.18862929],
       [-0.85195946, -1.33649464, -0.34787666, -0.05778816],
       [-0.85195946,  1.01510883, -1.25169694, -1.23535827],
       [ 1.96747474, -0.6310136 ,  1.40327514,  0.98894082],
       [-0.36162308, -1.10133429,  0.44296609,  0.07305296],
       [ 0.49646559, -0.6310136 ,  0.66892116,  0.8580997 ],
       [-0.11645489, -0.1606929 ,  0.32998855,  0.07305296],
       [ 1.10938607,  0.07446744,  1.1208313 ,  1.64314644],
       [ 0.74163378, -0.6310136 ,  1.1208313 ,  1.25062307],
       [-0.36162308, -1.57165498,  0.10403348, -0.05778816],
       [ 2.21264293, -0.1606929 ,  1.68571897,  1.25062307],
       [-0.85195946,  0.77994848, -1.19520818, -1.23535827],
       [ 0.0061292 , -1.10133429,  0.21701102,  0.07305296],
       [ 0.86421787, -0.6310136 ,  0.55594362,  0.46557633],
       [-0.23903899, -0.1606929 ,  0.49945485,  0.46557633],
       [-0.11645489, -0.6310136 ,  0.27349978,  0.20389408],
       [-1.21971175,  0.

In [76]:
from sklearn.neural_network import MLPClassifier
mlp =MLPClassifier(hidden_layer_sizes=(10,10),max_iter=2000)

In [77]:
mlp.fit(x_train , y_train.values.ravel())

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(10, 10), learning_rate='constant',
              learning_rate_init=0.001, max_iter=2000, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [78]:
predictions =mlp.predict(x_test)
predictions


array([0, 2, 1, 0, 1, 1, 2, 1, 1, 0, 2, 0, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1,
       1, 1, 2, 2, 0, 2, 0, 2], dtype=int64)

In [79]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test,predictions))

[[ 6  0  0]
 [ 0 11  1]
 [ 0  2 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       0.85      0.92      0.88        12
           2       0.91      0.83      0.87        12

    accuracy                           0.90        30
   macro avg       0.92      0.92      0.92        30
weighted avg       0.90      0.90      0.90        30

